### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by chenscottus** [haoqinx/fuyouCo#1]
Hello,

   I tried to use it in windows.
  
   After I am able to run the code, this function : static void mainfunc(uint32_t low32, uint32_t h32){
   this line cause the problem:  int id = sche -> runningCo_; 
  Unable to read memory
 
   Thanks,

**Comment by chenscottus** [comment]
In order to run it in windows, I changed in CoScheduler::CoScheduler()
    coroutines_.reserve(capacity_); 
     ==>
    coroutines_.resize(capacity_);
 
and download the Unix ucontext_t Operations on Windows Platforms from here:
     https://www.codeproject.com/Tips/4225/Unix-ucontext-t-Operations-on-Windows-Platforms

**Comment by haoqinx** [comment]
> Hello,
> 
> I tried to use it in windows.
> 
> After I am able to run the code, this function : static void mainfunc(uint32_t low32, uint32_t h32){ this line cause the problem: int id = sche -> runningCo_; Unable to read memory
> 
> Thanks,

This library is only available on Linux x86_ 64, please try running in WSL.
